#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code from Apache log file

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{printf("%d %s %s\n", $1, $2, $3)}'