#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code from Apache log file
# Displays data ordered by occurrence number

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn | sed 's/^[ ]*//'