#!/usr/bin/env bash
# Displays the contents of the current directory after the first dash

for file in *; do
    if [ -f "$file" ] && [[ $file != .* ]]; then
        echo "$file" | cut -d'-' -f2-
    fi
done
