#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely with
# "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
