#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with sleep 2
# and prints "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
